In [2]:
import numpy as np

In [4]:
dir(np)    #objects within package

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

In [3]:
len(dir(np))

620

#### numpy array is the main object/data structure in numpy package
     - numpy provides 1 array object/DS(holds data in certain manner) i.e numpy 


In [7]:
##  create an array object

l =[1,2,3,4,5,6]
print(type(l))
l

<class 'list'>


[1, 2, 3, 4, 5, 6]

In [10]:
# to create an array in python, that can be done only by numpy package

arr = np.array(l)  
print(type(arr))
arr

<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5, 6])

In [ ]:
nd.array - n dimensional array

#### Properties of list
      - ordered, indexable,mutable,hetrogenous data structure
      - duplicate members supported
      - any python data can be an element
#### Properties of array
      - ordered, indexable,mutable,homogenous data structure
      - duplicate members supported
      - any python data can be an element

In [12]:
#homogenous - all the elements in the sequence has to be of same type
l = [3.4,5.6,3.0]
arr = np.array(l)  
print(type(arr))
arr

<class 'numpy.ndarray'>


array([3.4, 5.6, 3. ])

In [13]:
l = ['3.4','5.6','3.0']
arr = np.array(l)  
print(type(arr))
arr

<class 'numpy.ndarray'>


array(['3.4', '5.6', '3.0'], dtype='<U3')

In [15]:
l = [3.4,5.6,3.0,1,2]
print(l)
arr = np.array(l)  
print(type(arr))   # if mixed type of elements are present, i.e. int float string, then it converts to same data type
arr

[3.4, 5.6, 3.0, 1, 2]
<class 'numpy.ndarray'>


array([3.4, 5.6, 3. , 1. , 2. ])

In [2]:
l = [3.4,5.6,3.0,1,2,'3']  # typecast to all string
print(l)
arr = np.array(l)  
print(type(arr))   
arr

[3.4, 5.6, 3.0, 1, 2, '3']
<class 'numpy.ndarray'>


array(['3.4', '5.6', '3.0', '1', '2', '3'], dtype='<U32')

In [4]:
# for list within list

l = [3.4,5.6,3.0,1,2,'3',[3,4],True,False]  # typecast to object
print(l)
arr = np.array(l)  
print(type(arr))   

arr

[3.4, 5.6, 3.0, 1, 2, '3', [3, 4]]
<class 'numpy.ndarray'>


<ipython-input-4-fb932885c073>:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  arr = np.array(l)


array([3.4, 5.6, 3.0, 1, 2, '3', list([3, 4])], dtype=object)

In [ ]:
# upcasting happens for data type in array
#int -> float -> string

#### create array 



In [5]:
# 1. empty()

arr = np.empty(10) # bydefault it takes numerical array of junk values of float type
print(type(arr))
arr

<class 'numpy.ndarray'>


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
arr = np.empty((2,3)) # 2D array of 2X3
print(type(arr))
arr

<class 'numpy.ndarray'>


array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
arr = np.empty((2,3,4)) # 3D array of 2X3X4 (rarely used)
print(type(arr))
arr

<class 'numpy.ndarray'>


array([[[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
         1.60218491e-306],
        [6.23053614e-307, 1.33512512e-306, 8.90095411e-307,
         1.33511018e-306],
        [1.33511969e-306, 1.24610383e-306, 1.69118108e-306,
         8.06632139e-308]],

       [[1.20160711e-306, 1.69119330e-306, 1.29062229e-306,
         1.60217812e-306],
        [1.37961370e-306, 1.02359848e-306, 1.60219035e-306,
         1.60220393e-306],
        [1.05700515e-307, 1.11261774e-306, 1.29060871e-306,
         8.34424766e-308]]])

In [8]:
arr = np.empty((2,3,4),dtype =int) #defining type of array
print(type(arr))
arr

<class 'numpy.ndarray'>


array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [9]:
#2. ones()

arr = np.ones(10) # all filled with 1's
print(type(arr))
arr

<class 'numpy.ndarray'>


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
arr = np.ones((2,3))
print(type(arr))
arr

<class 'numpy.ndarray'>


array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
#3. zeros() - hardcoding into 0's

arr = np.zeros(10)
print(type(arr))
arr

<class 'numpy.ndarray'>


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
arr = np.zeros((2,3))
print(type(arr))
arr

<class 'numpy.ndarray'>


array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
#4. linspace() -> returns evenly spaced array of elements, only creates 1D array

arr = np.linspace(start = 1,stop = 20,num =20) #num = no. of elements, and start stop are boundaries
print(type(arr))
arr

<class 'numpy.ndarray'>


array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20.])

In [16]:
arr = np.linspace(start = 1,stop = 20,num =10) 
print(type(arr))
arr

<class 'numpy.ndarray'>


array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [17]:
arr = np.linspace(start = 1,stop = 20,num =60) 
print(type(arr))
arr

<class 'numpy.ndarray'>


array([ 1.        ,  1.3220339 ,  1.6440678 ,  1.96610169,  2.28813559,
        2.61016949,  2.93220339,  3.25423729,  3.57627119,  3.89830508,
        4.22033898,  4.54237288,  4.86440678,  5.18644068,  5.50847458,
        5.83050847,  6.15254237,  6.47457627,  6.79661017,  7.11864407,
        7.44067797,  7.76271186,  8.08474576,  8.40677966,  8.72881356,
        9.05084746,  9.37288136,  9.69491525, 10.01694915, 10.33898305,
       10.66101695, 10.98305085, 11.30508475, 11.62711864, 11.94915254,
       12.27118644, 12.59322034, 12.91525424, 13.23728814, 13.55932203,
       13.88135593, 14.20338983, 14.52542373, 14.84745763, 15.16949153,
       15.49152542, 15.81355932, 16.13559322, 16.45762712, 16.77966102,
       17.10169492, 17.42372881, 17.74576271, 18.06779661, 18.38983051,
       18.71186441, 19.03389831, 19.3559322 , 19.6779661 , 20.        ])

In [18]:
arr = np.linspace(start = 1,stop = 20,num =10,endpoint = False) # last element need not be 20, it can be anything less than 20
print(type(arr))
arr

<class 'numpy.ndarray'>


array([ 1. ,  2.9,  4.8,  6.7,  8.6, 10.5, 12.4, 14.3, 16.2, 18.1])

In [ ]:
# in above code,it got 1.9 as interval to divide it into 10 equal parts and ended with anything other than 20

In [19]:
arr = np.linspace(start = 1,stop = 20,num =10,endpoint = False,dtype =int) 
print(type(arr))
arr

<class 'numpy.ndarray'>


array([ 1,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
#5. arange() -> 1D array only

arr = np.arange(1,10,0.5) # end is not included
print(type(arr))
arr

<class 'numpy.ndarray'>


array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [3]:
arr = np.arange(1,10) 
print(type(arr))
arr

<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr = np.arange(1,10,2) 
print(type(arr))
arr

<class 'numpy.ndarray'>


array([1, 3, 5, 7, 9])

In [13]:
# 6.random()

## randint()- returns random int value less than passed in argument(ex: for 5, everytime we run it give different int value b/w 0 to 4)

for i in range(1,11):
    arr = np.random.randint(5) 
    print(arr)

1
4
4
1
0
4
2
4
1
0


In [12]:
for i in range(1,11):
    arr = np.random.randint(5,10) # gives random int b/w 5 to 9(end is exclusive)
    print(arr)   

9
5
7
6
6
9
7
6
8
5


In [15]:
arr = np.random.randint(5,10,size = 10) #returns 1D array
arr

array([9, 5, 5, 7, 8, 9, 7, 5, 9, 5])

In [16]:
arr = np.random.randint(5,10,size = (5,2)) # 2D array
arr

array([[8, 9],
       [6, 9],
       [7, 5],
       [5, 7],
       [9, 7]])

In [17]:
## randn() - gives random floating numbers, boundary is from -infinity to +infinity

arr = np.random.randn(5) # 1D array
arr

array([ 1.07663572, -1.62370783, -0.63190577, -0.77659601, -0.17731497])

In [18]:
arr = np.random.randn(5,2) # 2D array
arr

array([[ 0.89762939, -1.82005035],
       [-0.2505341 ,  0.39711909],
       [ 0.19478059, -0.56401061],
       [ 0.81876103, -1.1732355 ],
       [-0.1299778 ,  0.90406997]])

#### Accessing elements of an array

In [19]:
arr = np.linspace(start = 1,stop = 20,num =10,endpoint = False) 
print(type(arr))
arr

<class 'numpy.ndarray'>


array([ 1. ,  2.9,  4.8,  6.7,  8.6, 10.5, 12.4, 14.3, 16.2, 18.1])

In [22]:
print(arr[0])
print(arr[9])
print(arr[-1])

1.0
18.099999999999998
18.099999999999998


In [38]:
arr = np.random.randn(5,5) 
arr

array([[ 0.40197063, -0.98329838,  0.50958254, -0.0827218 ,  1.28564473],
       [-0.86508916, -1.80486306,  2.48504213, -0.19539179,  0.11841176],
       [-0.17269629,  0.63548538,  1.16914179,  0.34640889, -1.49532796],
       [ 1.25289198,  0.14899917,  0.84389299,  0.51639888, -0.14785659],
       [-1.93695276, -0.02467033,  1.39864268,  1.0038939 ,  1.24252118]])

In [39]:
# fetch middle 3 rows
arr[1:4]  # slicing

array([[-0.86508916, -1.80486306,  2.48504213, -0.19539179,  0.11841176],
       [-0.17269629,  0.63548538,  1.16914179,  0.34640889, -1.49532796],
       [ 1.25289198,  0.14899917,  0.84389299,  0.51639888, -0.14785659]])

In [23]:
arr = np.random.randn(5,2) 
arr

array([[-0.90447224, -0.34523884],
       [-0.51185431, -0.14983283],
       [-0.53060634, -0.32762986],
       [ 0.98077114, -0.01251808],
       [-1.01430943,  0.03497762]])

In [24]:
# fetch 1st element
print(arr[0][0])

-0.9044722401759868

In [26]:
print(arr[1][0]) #2nd row,1st element
print(arr[3][1]) #fetch 0.01251808 (or arr[-2][-1])

-0.5118543064530857
-0.012518080303228058


In [28]:
# we can also fetch elements using below approach(only applicable for array and not list)

print(arr[0,0])
print(arr[1,0])
print(arr[-2,-1]) # more efficient way of indexing performance wise rather than obj[i][j] in array

-0.9044722401759868
-0.5118543064530857
-0.012518080303228058


In [30]:
arr[0:2]

array([[-0.90447224, -0.34523884],
       [-0.51185431, -0.14983283]])

In [31]:
l = list(range(1,10))
l

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [32]:
# add a value of 2 to each element

[x+2 for x in l ]

[3, 4, 5, 6, 7, 8, 9, 10, 11]

In [33]:
# can do it using array 
arr =np.array(l)  #converts list to array
arr+2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [34]:
arr*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [35]:
arr**2

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [36]:
arr/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [37]:
arr+arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [41]:
arr = np.array([1,2,3,'4'])
arr

array(['1', '2', '3', '4'], dtype='<U11')

In [42]:
arr[-1] = 4 #it wont modify to int as it is upcasted to string type and it wont downcast to int(as it violates the rule of array)
arr

array(['1', '2', '3', '4'], dtype='<U11')

In [2]:
# slicing middle values
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [3]:
# fetching middle values
arr[1:3,1:4]  # arr[row,col]

array([[ 7,  8,  9],
       [12, 13, 14]])

In [48]:
arr[1:3] 

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
### array methods:

# sum(),mean(),max(),array(),reshape(),dot(),min(),std(),percentile()  # widely used

In [4]:
arr = np.linspace(start = 1,stop = 20,num =10,endpoint = False) 
print(type(arr))
arr

<class 'numpy.ndarray'>


array([ 1. ,  2.9,  4.8,  6.7,  8.6, 10.5, 12.4, 14.3, 16.2, 18.1])

In [5]:
arr.reshape((2,5))

array([[ 1. ,  2.9,  4.8,  6.7,  8.6],
       [10.5, 12.4, 14.3, 16.2, 18.1]])

In [6]:
arr1 = np.linspace(start = 1,stop = 20,num =10,endpoint = False) 
arr2 = np.linspace(start = 1,stop = 20,num =10,endpoint = False) 
arr3 = np.linspace(start = 1,stop = 20,num =11,endpoint = False) 

In [9]:
print(arr1+2)
print(arr1+arr2)  #elementwise addition
print(arr1*arr2)

[ 3.   4.9  6.8  8.7 10.6 12.5 14.4 16.3 18.2 20.1]
[ 2.   5.8  9.6 13.4 17.2 21.  24.8 28.6 32.4 36.2]
[  1.     8.41  23.04  44.89  73.96 110.25 153.76 204.49 262.44 327.61]


In [8]:
print(arr1+arr3)  #invalid as no of elements differ

ValueError: operands could not be broadcast together with shapes (10,) (11,) 

In [10]:
np.mean(arr1)

9.549999999999999

In [ ]:
np.dot()  #performs matrix multiplication

In [11]:
# requirement for matrix multiplication -> no of columns in 1st matrix should be equal to no of rows in 2nd matrix

arr1 = np.linspace(start = 1,stop = 20,num =10,endpoint = False).reshape(5,2) 
arr2 = np.linspace(start = 1,stop = 20,num =10,endpoint = False).reshape(2,5)  # for reshape(6,2) it will give error since 6!=2
arr1.dot(arr2)

array([[ 31.45,  38.86,  46.27,  53.68,  61.09],
       [ 75.15,  97.  , 118.85, 140.7 , 162.55],
       [118.85, 155.14, 191.43, 227.72, 264.01],
       [162.55, 213.28, 264.01, 314.74, 365.47],
       [206.25, 271.42, 336.59, 401.76, 466.93]])